### ISSUE TITLE
More Examples, Please!

### ISSUE THREAD

**Issue by Miserlou** [tea-lang-org/tea-lang#1]
This project looks very interesting and useful, but you need a lot more tutorials/practical examples so that lay-folk like me try with our own data!

**Comment by emjun** [comment]
I'm adding examples here as users allow me to share them: https://github.com/emjun/tea-lang/tree/master/examples

**Comment by emjun** [comment]
@meli365 added more examples, and we will continue to add more/update as we improve Tea! 

Keep an eye out! 

For now: https://github.com/emjun/tea-lang/tree/master/examples
