### ISSUE TITLE
Missing dependencies in python package

### ISSUE THREAD

**Issue by g-simmons2** [tea-lang-org/tea-lang#15]
Hi, not sure if this is an issue with package dependencies or an issue of compatibility between pip and conda. 

After creating an environment like so:
`conda create -n testing_tea python=3.7`

And installing tea:
`conda activate testing_tea`
`pip install tealang`

The install process shows no errors, but when attempting to `import tea`, I get a 
 `ModuleNotFoundError` for pandas, followed by a number of other packages. This is resolved by installing everything in the pipfile by hand. 

I would guess that a lot of people (like me) who would be interested in the project are accustomed to using conda, so smoothing this out would be beneficial. 

Very cool work by the way, looking forward to further development and added features 👍

**Comment by emjun** [comment]
Hi @g-simmons2 ! So sorry for the latency. 

GREAT point! I hadn't run into this issue before. Let me look into how I can make the installation process easier for Conda users!

Be in touch...
Eunice

**Comment by jrpereirajr** [comment]
By the way, those're all packages needed (at version 0.0.10):
`pip install tealang pandas scipy sklearn statsmodels bootstrapped z3-solver`
HTH

**Comment by russelldb** [comment]
Even after using the pip install line above I still have the error `AttributeError: module 'z3' has no attribute 'BoolSort'
`

**Comment by MaLiN2223** [comment]
This should be working now. 
I have installed `tealang` with conda environment with commands provided by OP and everything worked fine. 
I think we can close this issue, new users can open a new one. 

cc @emjun
