### ISSUE TITLE
Setting the right values in "variables", "assumptions", "experimental_design" and "hypothesis" in the python script based on the attached sample data.

### ISSUE THREAD

**Issue by chijiokeonukem** [tea-lang-org/tea-lang#18]
Setting the right values in variables, assumptions, experimental_design and hypothesis in the python script based on the attached sample data. We hypothesis that AR will be higher than TV. ie AR >TV.

[sample_data.txt](https://github.com/emjun/tea-lang/files/3644553/sample_data.txt)

**Comment by emjun** [comment]
I added your data and a sample Tea program to analyze it in the repo [https://github.com/emjun/tea-lang/tree/master/examples/AR_TV](url)

`ar_tv.csv` is a CSV of the data you gave (as a .txt file).
`ar_tv_long.csv` is a CSV in *long format* for your data.
`ar_tv_tea.py` is the Tea program!

You may have to change the `data_path` in the `ar_tv_tea.py` file, but it runs on my machine! Let me know what results you get. We can compare notes! :)

If you're wondering how I changed `ar_tv.csv` int long format, see the `longify.py` script [here](https://github.com/emjun/tea-lang/tree/master/examples).

**Comment by emjun** [comment]
@chijiokeonukem - I haven't heard from you, so I am going to assume this issue is resolved.
