### ISSUE TITLE
Issues with wilcoxon and mannwhitney_u tests

### ISSUE THREAD

**Issue by alexkyllo** [tea-lang-org/tea-lang#2]
- Scipy's implementation of the Wilcoxon signed-rank and Mann-Whitney tests use the normal approximation to calculate the p-value, therefore it's recommended to only use them when _n_ > 20 (see Notes section at: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html). Perhaps a constraint on minimum value of _n_ could be added for this test? Or a function could be added to Tea to implement calculating the exact p-value when _n_ <= 20.
- Tea ignores whether the hypothesis is two-sided or one-sided for these tests. For the test `test_integration.test_wilcoxon_signed_rank`, which is a paired-samples test with a one-sided hypothesis, it reports the same result (two-sided p-value) regardless of whether you do 
`tea.hypothesize(['day', 'value'], ['day:sundayBDI > wedsBDI'])` or
`tea.hypothesize(['day', 'value'], ['day:sundayBDI < wedsBDI'])` . It is possible to apply the test to a one-sided hypothesis, but `scipy.stats.wilcox` does not support this. So Tea should either add a constraint that only applies this test if the user's hypothesis is two-sided, or it should implement a one-sided version of the Wilcoxon signed-rank test.
- Tea throws an exception when I try to change this to a two-sided hypothesis by specifying `'day:sundayBDI != wedsBDI'` :
```python
>>> tea.hypothesize(['day', 'value'], ['day:sundayBDI != wedsBDI'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/projects/tea-lang/tea/api.py", line 131, in hypothesize
    relationship = relate(v_objs, prediction)
  File "/mnt/d/projects/tea-lang/tea/build.py", line 321, in relate
    return Relate(vars, predict(vars, prediction))
  File "/mnt/d/projects/tea-lang/tea/build.py", line 299, in predict
    pred = create_prediction(categorical_prediction, vars, p)
  File "/mnt/d/projects/tea-lang/tea/build.py", line 223, in create_prediction
    assert(rhs in var.categories.keys())
AssertionError
```
- `scipy.stats.mannwhitney_u` can do a one-sided test on two independent samples, but Tea hardcodes `alternative='two-sided'`. The `alternative` parameter should instead be set depending on the direction of the user's hypothesis.

Just for comparison, note that R's `wilcox.test` function can handle one-sample/two paired samples or two independent samples, one-sided or two-sided, and calculates either exact or normal-approximate p-values, defaulting to exact when _n_ < 50.

**Comment by emjun** [comment]
- P-values for Wilcoxon signed-rank test: Added implementation - see ``wilcox_signed_rank_exact`` function in ``evaluateHelperMethods.py``
- P-values for Mann-Whitney U test: Added implementation - see ``mann_whitney_exact`` in ``evaluateHelperMethods.py``
- One-sided test for Wilcoxon signed-rank test: It looks like [``scipy.stats.wilcoxon``](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html) supports two-sided and one-sided tests. However, Tea was defaulting to using the two-sided test. Tea now sets the appropriate one-sided/two-sided parameter for ``scipy.stats.wilcoxon``.
- Hypothesis exception: I can't reproduce your bug, but we did refactor the hypothesis functionality.  I think we may have fixed this bug.
- One-sided test for Mann-Whitney U: Tea now picks which one-sided vs. two-sided test to conduct based on the end-user's hypothesis. 

Finally, notes on R: Thanks for summarizing! It was helpful to have a few concrete comparison points. Now, Tea will handle one- and two-sided Mann-Whitney U and Wilcox Signed Rank tests. For both, when n < 20, the exact p-value is computed. When n >20, the normal-approximate p-values from Scipy/statsmodels are used.
