### ISSUE TITLE
Better type checking in `api.py`

### ISSUE THREAD

**Issue by g-simmons2** [tea-lang-org/tea-lang#20]
The error message in [this example](https://github.com/g-simmons2/testing_tea/blob/master/ipynb/bug_example_load_from_df.ipynb) also suggests that better type-checking of the user-specified data objects may be useful.

`tea.hypothesize()` checks that the dataset path has been specified like so:

 `assert(dataset_path)`

The user could wrongly call tea.data() on other types of objects besides the desired type (string) and the assertion here would not fail. Without thinking about support for other data objects, I would suggest checking that the dataset_path is actually a string.

**Comment by emjun** [comment]
Great point! 

For the short term, I went ahead and updated Tea based on your suggestion to check that the file parameter to `data(file)` is a string or Path object. 

In the longer term, I am in the beginning stages of of re-writing Tea's frontend to use [Lark](https://github.com/lark-parser/lark), which I hope will a) clean up the API and b) more systematically support this kind of type checking and other parsing errors. Check out the latest in [this branch](https://github.com/emjun/tea-lang/tree/lark_parser), all contributions (including issues) very strongly appreciated! 😄 

As for your suggestion and your other open issue on supporting additional inputs/forms of data, I'm working on it! Thanks for all your great issues/suggestions!

**Comment by g-simmons2** [comment]
Awesome, thank you!
