### ISSUE TITLE
Error on example publish on ACM UIST 2019

### ISSUE THREAD

**Issue by jrpereirajr** [tea-lang-org/tea-lang#24]
Hi there.

First, congratulations for your job! :)

I read your paper on ACM UIST 2019 and tried out to run example of 'Figure 3: Tea program and its mode-dependent executions' (page 5), but got some errors.

The notebook (and the error output) could be found here: https://colab.research.google.com/drive/1y7HUVEbu1YvyRbZ1xDYPIE6IK-sjPpOm

The error occured when method hypothesize() was executed. It's seems to be some kind of wrong array key error but I couldn't find out what key is wrong... Could you help me, please?

Please, let me know if you need more information.

Thank you,
José

**Comment by emjun** [comment]
Thanks so much for your encouragement and issue, @jrpereirajr ! 

The key error is basically that Tea can't find the column specified in the program ('Life Exp').
It looks like the dataset you are using (http://www.mc-oman.on-rev.com/R/resources/DataFiles/Statex77.csv) has a column labeled 'Life.Exp'. The Tea program expects 'Life Exp' (space, not period/dot). 

Try it out again and let me know if the error persists!

Your error reminds to improve error reporting!!

Eunice

**Comment by jrpereirajr** [comment]
Hi @emjun !

Um... I knew that would probably be a noob-noob question... Now it's working :)
Thank you for your help!

I updated code, for someone who wants a new example:
https://github.com/jrpereirajr/snippets/tree/master/tea
or
https://colab.research.google.com/drive/1y7HUVEbu1YvyRbZ1xDYPIE6IK-sjPpOm#scrollTo=GAbF_apmsVxV

José
