### ISSUE TITLE
Default Alpha Value Not Recognized

### ISSUE THREAD

**Issue by meli365** [tea-lang-org/tea-lang#39]
Based on [given descriptions](http://tea-lang.org/), Tea should be able to run without any assumptions passed by the user, with a default alpha value of 0.05.

I tried running [ar_tv_tea.py](https://github.com/emjun/tea-lang/blob/master/examples/AR_TV/ar_tv_tea.py) with line 35 commented out so that `tea.assume(assumptions)` does not execute.

This resulted in the following error message:

```
Traceback (most recent call last):
  File "C:/Users/Melissa Birchfield/PycharmProjects/tea-lang/examples/AR_TV/ar_tv_tea.py", line 37, in <module>
    results = tea.hypothesize(['Score', 'Condition'], ['Condition:AR > TV'])
  File "C:\Users\Melissa Birchfield\PycharmProjects\tea-lang\tea\api.py", line 166, in hypothesize
    result = evaluate(dataset_obj, relationship, assumptions, study_design)
  File "C:\Users\Melissa Birchfield\PycharmProjects\tea-lang\tea\evaluate.py", line 357, in evaluate
    combined_data = BivariateData(vars, study_type, alpha=float(assumptions['alpha'])) 
KeyError: 'alpha'
```

It looks like `evaluate.py` does not account for the possibility that the assumptions could fail to include an alpha value.

I also took a closer look at `api.py` and `solver.py`. In both files, the default alpha value is set to 0.01, not 0.05.

**Comment by MaLiN2223** [comment]
#41 should fix the `KeyError` problem. 
@emjun, could we get an input about the values of `0.01` ? I was not sure if this is something we want to change or not. I can address this in the above PR or a separate one if needed.

**Comment by emjun** [comment]
Let's keep the default as 0.05 unless the end-user overrides in their Tea program by setting an assumption for Tea to use 'alpha' = <anything, could be 0.01>

**Comment by emjun** [comment]
@MaLiN2223 Could you address this issue in the same above PR? I'll then review and then merge all the changes related to alpha at once.

**Comment by MaLiN2223** [comment]
@emjun the before mentioned alphas were adressed in the PR.
