### ISSUE TITLE
Evaluate function fails for Equal, NotEqual, LessThan, LessThanEqual, GreaterThan, GreaterThanEqual

### ISSUE THREAD

**Issue by MaLiN2223** [tea-lang-org/tea-lang#42]
`evaluate` function fails for Equal, NotEqual, LessThan, LessThanEqual, GreaterThan, GreaterThanEqual nodes with exception 
`TypeError: __init__() missing 2 required positional arguments: 'lhs' and 'rhs'`

For example in `evaluate(ANY, NotEqual(), ANY)`

This is caused by lines similar to 
https://github.com/emjun/tea-lang/blob/76de2d7551500a623b6c49e5e3dc250d8da13318/tea/evaluate.py#L66
 where the call is missing an argument
@emjun, I don't know if this is something worth fixing. Just want to make sure that we are not planning to remove or rewrite them.

**Comment by emjun** [comment]
Let me look into this some more over the next couple of days. Thanks for bringing this to my attention.
