### ISSUE TITLE
Enforce style checks 

### ISSUE THREAD

**Issue by MaLiN2223** [tea-lang-org/tea-lang#52]
As per our discussion in #51, this issue is to track enforcing style checkers. 
I expect this to be done only on the new branch, the old code would stay as is.

**Comment by emeryberger** [comment]
I've been using [Black](https://github.com/psf/black), which is IMHO better than a style checker -- it simply forcibly re-formats your files. I think it does a nice job.

[isort](https://pypi.org/project/isort/) is also nice, enforcing style on imports.

**Comment by MaLiN2223** [comment]
Good call @emeryberger 
I was personally using flake8 + autopep8 locally but black is also a viable option. 

I would like to introduce 'no merge' policy for not formated commits. I think any pre-hook can be skipped when doing a PR, no?

**Comment by emjun** [comment]
I think we can use [Github Actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions) to enforce style checks and reformatting. 

We can also set conditions for when the actions should be skipped. Here is an [example](https://github.com/marketplace/actions/skip-based-on-commit-message) that skips based on the commit message. 

Both require us to use YAML, and I'm fine with that.

Thoughts?

**Comment by MaLiN2223** [comment]
Closing in favour of #56
