### ISSUE TITLE
missing sympy dependancy

### ISSUE THREAD

**Issue by AaronWatters** [tea-lang-org/tea-lang#54]
Just tried to install tea in a fresh py3.7 conda environment and I see this when I run the test notebook:

```
~/repos/tea-lang/tea/helpers/evaluateHelperMethods.py in <module>
     21 import math
     22 from scipy.special import comb
---> 23 from sympy.utilities.iterables import multiset_permutations
     24 
     25 import pandas as pd

ModuleNotFoundError: No module named 'sympy'
```

Apparently it is not listed in the install dependancies?

**Comment by emjun** [comment]
Ah! You are correct. Sorry about that. I just patched this, rebuilt Tea with the feature that you can upload data from a pandas dataframe (not just a CSV), and uploaded a new version to Pypa: https://pypi.org/project/tealang/0.3.0/. 

Try ``pip install --upgrade tealang`` Hope that fixes your issues for you! If not, let me know :)
